# Generated by Django 4.0.3 on 2022-03-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['date'], 'verbose_name': 'Peticion', 'verbose_name_plural': 'Peticiones'},
        ),
        migrations.RenameField(
            model_name='request',
            old_name='algoritmo',
            new_name='algorithm',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='status_respuesta',
            new_name='response_status',
        ),
    ]
