# Generated by Django 4.0.3 on 2022-03-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='body',
            new_name='frase_enviada',
        ),
    ]
