# Generated by Django 4.0.3 on 2022-03-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_rename_body_request_frase_enviada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='bot_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='conversation_id',
            field=models.UUIDField(null=True, verbose_name='ID conversacion'),
        ),
        migrations.AlterField(
            model_name='request',
            name='site_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
